title: Nikoleta E. Glynatsi
email: GlynatsiNE@cardiff.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Nikoleta E. Glynatsi
# the subpath of your site, e.g. /blog
baseurl: "/talks"
url: ""
twitter_username: NikoletaGlyn
github_username:  Nikoleta-v3
plus_username: "+NikoletaGlynatsi"


markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
plugins: [jekyll-gist]
permalink: /:year/:month/:title.html
